# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.app.name }}
    environment: [[ .Environment ]]
    version: {{ .Values.image.tag }}
    AccountableTeam: Inventory
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: {{ .Values.app.name }}